[package]
name = "controls"
version = "0.1.0"
authors = ["Josh Hejna <josh.hejna@gmail.com>"]
edition = "2018"

[dependencies]
alga = "0.7.2"
dimensioned = "0.7.0"
serde = "1.0.0"
csv = "1.0.0"
approx = "0.3.0"
